### ISSUE TITLE
Does CT rate averaging count a CT rate of zero for the same class?

### ISSUE THREAD

**Issue by JanekEbb** [audioanalytic/psds_eval#5]
https://github.com/audioanalytic/psds_eval/blob/6c3f263fba95c9fc6557adf416e61af2e96b19d0/src/psds_eval/psds.py#L651

Hi,

could it be that the cross trigger rate averaging in line 651 is not only done over other classes, as proposed in Eq. (6) of your paper, but includes a zero for the same class, given that the ct_rate matrix is initialized with zeros in line 405?

**Comment by tgrainge** [comment]
HI @JanekEbb 

I am investigating this issue that you raised. I will get back to you shortly with a resolution.

Kind Regards

Tom

**Comment by tgrainge** [comment]
Hi @JanekEbb 

The commit f8a591a5b1836928eb1be2324be8dcdb4e9cc49a should solve this issue. It makes use of np.nan when initialising arrays to ensure that the initial values are ignored when calculating the efpr. It is available in the released version 0.5.0. 

Kind Regards

Tom
